version: "3.9"

services:
  knowledge_base:
    build: ./knowledge_base
    container_name: prolog_kb
    ports:
      - "5000:5000"
  frontend:
    build: ./frontend
    container_name: flutter_frontend
    ports:
      - "8080:9000"
    